on: [push]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building
        shell: cmd
        run: |
          echo Phrase 1
          CD.bat 10.0.16
          echo Phrase 2
          .\7z\7za a -tzip Build.zip .\Build -y
          echo Done
      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Build.zip
          asset_name: Build.zip
          tag: Current
          overwrite: true
          body: "Automatic Release"
