on: [push]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building
        shell: cmd
        run: |
          build.bat 10.0.16
          echo Phrase 1 Done
          .\7z\7za a -tzip Build.zip .\Build -y
          echo Phrase 2 Done
      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Build.zip
          asset_name: Build.zip
          tag: Stable
          overwrite: true
          body: "Auto Release"

  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Test
      - run: echo %PATH%
