on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Test
      - run: echo %cd%
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: readme.md
          asset_name: test
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
