on: [push]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building
        shell: cmd
        run: |
          CD.bat 10.0.16
          echo Done
      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Build.zip
          asset_name: Build.zip
          tag: Auto Release
          overwrite: true
          body: "Automatic Release"

  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Test
      - run: echo %PATH%
