on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Build
        uses: actions/checkout@v2
        run: build.bat 10.0.16
        run: .\7z\7za a -tzip Build.zip .\Build -y
        shell: cmd
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Build.zip
          asset_name: Build.zip
          tag: Stable
          overwrite: true
          body: "Auto Release"

  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Test
      - run: echo %cd%
